### ISSUE TITLE
Buffer support

### ISSUE THREAD

**Issue by maskeddd** [MaxOhn/rosu-pp-js#2]
Just wondering if it would be possible to add support for buffers instead of just file paths.

**Comment by MaxOhn** [comment]
Definitely possible since rosu itself supports it, I just didn't add it to the binding.
It won't be particularly high on my priority list though so it might take some good time but I'll see to it eventually.

**Comment by MaxOhn** [comment]
Added in v0.9.1 🎉 

Instead of a `Buffer` it accepts a `Uint8Array` but since `Buffer` is a subclass, it works the same way.
