### ISSUE TITLE
Error: Failed to parse beatmap: expected `osu file format v` at file begin

### ISSUE THREAD

**Issue by nyakokitsu** [MaxOhn/rosu-pp-js#5]
Error: Failed to parse beatmap: expected `osu file format v` at file begin
https://osu.ppy.sh/osu/2133551

**Comment by MaxOhn** [comment]
Works fine for me on map [/b/4488341](https://osu.ppy.sh/beatmapsets/2133551#osu/4488341) (downloaded through <https://osu.ppy.sh/osu/4488341>) which I assume you meant. Maybe your downloaded file is empty potentially due to networking issues?

**Comment by nyakokitsu** [comment]
I use an axios to get a file and import into your library through `fromContent`

**Comment by nyakokitsu** [comment]
> Works fine for me on map [/b/4488341](https://osu.ppy.sh/beatmapsets/2133551#osu/4488341) (downloaded through https://osu.ppy.sh/osu/4488341) which I assume you meant. Maybe your downloaded file is empty potentially due to networking issues?

Even with your bitmap does not work(

**Comment by MaxOhn** [comment]
Does the content of your downloaded file look normal when you open it manually? Its first line should be `osu file format v14`.

**Comment by nyakokitsu** [comment]
> Does the content of your downloaded file look normal when you open it manually? Its first line should be `osu file format v14`.

Yes it looks like this

**Comment by MaxOhn** [comment]
Can't reproduce it. Perhaps a code snippet could help figuring out your mistake.

**Comment by MaxOhn** [comment]
Closing this one, should be resolved with v1.0.0 anyway since beatmap parsing now works differently.
