### ISSUE TITLE
Some mod pp's are wrong

### ISSUE THREAD

**Issue by puk06** [MaxOhn/rosu-pp-js#8]
I came here to say that the PP calculations for some of the mods were wrong.

```js
const map = fs.readFileSync('test.osu', 'utf-8'); //https://osu.ppy.sh/beatmapsets/1856862#taiko/3825077
const beatmap = new rosu.Beatmap(map);

//HD: 8
//HR: 16
//EZ: 2
//DT: 64
//HT: 256

let difficultyArgs = {
    mods: Tested with the above values.
};

let difficulty = new rosu
    .Difficulty(difficultyArgs)
    .calculate(beatmap);

const PP = new rosu
    .Performance()
    .calculate(difficulty);

console.log(PP.pp);
```
**Result**
Original PP => rosu-pp-js
HDSS: **759**pp => **692.3902281341881**(same as NM)
HRSS: **779**pp => **751.8363331710395**
EZSS: **620**pp => **643.6490906614597**
DTSS: **1275**pp => **1275.1074471835482**(Correct)
HTSS: **439**pp => **439.4615725388199**(Correct)

The calculation seems to be correct for mods that change speed.

**Comment by MaxOhn** [comment]
~~Mh true, can easily reproduce these incorrect values. Will work on a fix ASAP~~ 👍

**Comment by MaxOhn** [comment]
Actually, everything is working as intended.

Difficulty attributes don't contain arguments that were passed to the difficulty calculation. Hence, when using those attributes instead of using a beatmap, arguments still have to be specified, namely the same ones you used for calculating the difficulty attributes.

```js
const map = fs.readFileSync('test.osu', 'utf-8'); //https://osu.ppy.sh/beatmapsets/1856862#taiko/3825077
const beatmap = new rosu.Beatmap(map);

let difficultyArgs = {
    mods: Tested with the above values.
};

let difficulty = new rosu
    .Difficulty(difficultyArgs)
    .calculate(beatmap);

const PP = new rosu
    .Performance(difficultyArgs) // <-
    .calculate(difficulty);

console.log(PP.pp);
```

This one works.

**Comment by puk06** [comment]
Sorry, I didn't understand "Same field as `Difficulty`, but also the next field:" in the performance section, I thought if I passed the mod with Difficulty it would work.
It is working properly now! Thank you!!
